Update dependencies
Idein/dockworker pull request #122
Opened 2022-06-15 01:38 UTC by dalance

This PR updates dependencies to resolve vulnerabilities.

2022-06-15 03:26 UTC, dalance commented
This will resolve #75, #119, #96

2022-06-15 12:50 UTC, eldesh requested changes
Can you separate PR from this for updating deprecated API (Docker::containers)?

2022-06-15 12:50 UTC, eldesh commented on src/hyper_client.rs
> -    Ok(Uri::from_str(&joined).context(ErrorKind::InvalidUri { var: joined })?)
The value `var` of ` InvalidUri` is required.
This is because we need to know what string caused the parsing error when we tried to parse it.

2022-06-15 12:50 UTC, eldesh commented on src/hyper_client.rs
> -        let url = Uri::from_str(&addr_https).context(ErrorKind::InvalidUri { var: addr_https })?;
same above

2022-06-15 12:50 UTC, eldesh commented on src/hyper_client.rs
> -        let url = Uri::from_str(&addr_https).context(ErrorKind::InvalidUri { var: addr_https })?;
same above

2022-06-17 07:15 UTC, eldesh commented
Looks good :+1:
Thank you for your contribution!

2022-06-17 07:15 UTC, merged