care the case docker dies
Idein/dockworker pull request #136
Opened 2023-02-14 02:52 UTC by cutsea110

Don't panic if the docker dies while reading the response body and the read fails unexpectedly.

2023-02-14 06:46 UTC, eldesh requested changes
commented.

2023-02-14 06:46 UTC, eldesh commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
Does this error always indicate the end of content?

2023-02-14 07:02 UTC, cutsea110 commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
It is certainly not the end of content.
I guess all I can say is, "Failed to get all of respons body".

How about error kind as ErrorKind::Other and error message as "failed to get all of response body"?

2023-02-14 07:12 UTC, eldesh commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
Shouldn't we first categorize the possible errors and then consider how to handling them?

Can we really only classify **all of the hyper::Errors** as ErrorKind::Other?

2023-02-14 07:23 UTC, cutsea110 commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
You mean, let's define a function which has the type `hyper::Error -> io::Error`, right?

2023-02-14 07:37 UTC, eldesh commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
Yes, it is approximately right.
I think in general it should be `hyper::Error -> Result<usize, io::Error>`. (i.e., normal error handling).

2023-02-14 08:01 UTC, cutsea110 commented on src/hyper_client.rs
> +                        "continuous reading of the response body ended unexpectedly",
Sorry, what does `usize` represent?

2023-02-15 01:07 UTC, cutsea110 commented on src/hyper_client.rs
> +fn convert_hyper_error_to_io_error<T>(e: &hyper::Error) -> std::result::Result<T, std::io::Error> {
I have categorized the errors.
Since hyper::Error does not expose the value, it is sorted by predicate.
Please let me see if there is any classification that you find incongruous.

2023-02-15 07:16 UTC, eldesh approved these changes
Looks good!

2023-02-15 07:16 UTC, eldesh commented on src/hyper_client.rs
> +fn convert_hyper_error_to_io_error<T>(e: &hyper::Error) -> std::result::Result<T, std::io::Error> {
It looks fine.
But I don't think it is necessary to return `T`. `err -> Result<T,E>` is just a general type of error handling code.

2023-02-15 07:52 UTC, cutsea110 commented
Thunks for your review!

2023-02-15 07:53 UTC, merged