Feat/add port mapping
Idein/dockworker pull request #152
Opened 2024-02-01 06:23 UTC by tawashichan

2024-02-01 06:51 UTC, garasubo commented on src/options.rs
> +pub struct ExporsedPorts(pub Vec<(u16, String)>);
stringではなくenumにしたほうがいい気がする（とりあえずはこのままでもよい）

2024-02-01 06:59 UTC, tawashichan commented
<img width="742" alt="スクリーンショット 2024-02-01 15 58 30" src="https://github.com/Idein/dockworker/assets/31276400/060f394e-820f-439c-b962-4a0ec607ff6c">
exampleにnginxのコンテナ動かす実装いれて動作確認できました

2024-02-01 06:59 UTC, garasubo commented on src/options.rs
> +        for (port, protocol) in &self.0 {
forループ回さなくても、`self.0.iter().map(..).collect()`してhashmapをつくるほうが個人的には好み（これもそのままでもいいかな）
参考: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=d6d3bdac0b11717a3b2a8a97159c2a4e

2024-02-01 07:01 UTC, garasubo commented on src/options.rs
> +    port_bindings: Option<PortBindings>,
port_bindingはhost_configの中にいるべき

2024-02-01 07:02 UTC, garasubo requested changes
port_bindingがhost_configの中にいないのはAPIの定義と異なるのでそこだけ修正が必要だと思います。ほかはおまかせします

2024-02-01 07:03 UTC, garasubo commented
あとCIが落ちているので`cargo fmt`も必要そう

2024-02-01 07:05 UTC, tawashichan commented on src/options.rs
> +    port_bindings: Option<PortBindings>,
何故仕様に従っていないのに正常に動作してしまったのか...

2024-02-01 07:36 UTC, tawashichan commented on src/options.rs
> -    host_config: Option<ContainerHostConfig>,
ContainerHostConfigをnewした後にport_bindingsだけ設定したものをここに設定すると,添付画像のようなエラーが出るようになってしまい,デフォルト挙動と挙動が変わるらしいことがわかった。
<img width="544" alt="スクリーンショット 2024-02-01 16 34 31" src="https://github.com/Idein/dockworker/assets/31276400/fab1282b-7761-4bbe-bcb0-2123353c444c">
デフォルト挙動を維持したいので,host_configを定義し直して,port_binding以外はなにも指定しないように変更した

2024-02-01 07:40 UTC, garasubo commented on src/options.rs
> -    host_config: Option<ContainerHostConfig>,
ContainerHostConfigがデフォルト値で0やら空vecを突っ込んでいるのが原因っぽいですね。多分全部optionalに変えてしまえば大丈夫な気がする

2024-02-01 08:09 UTC, garasubo requested changes
`ContainerHostConfig`のデフォルト値を変えるのが正しい変更かと思います。breaking_changeも許容されるのかなと思ったので、一旦フィールドを全削除してもいいかなと思います

2024-02-02 05:30 UTC, garasubo commented on src/docker.rs
> +    #[ignore]
nginxのイメージを引っ張ってくるのが大変なのでignoreしている？

2024-02-02 05:32 UTC, garasubo approved these changes
CIが通ればLGTM

2024-02-02 05:34 UTC, tawashichan commented on src/docker.rs
> +    #[ignore]
docker daemonが起動していないとダメなのでignoreしました

2024-02-02 05:35 UTC, tawashichan commented on src/docker.rs
> +    #[ignore]
コメント書いておきます

2024-02-02 10:13 UTC, legokichi approved these changes

2024-02-02 10:14 UTC, merged